all: monte_carlo_solution monte_carlo_init

monte_carlo_solution: monte_carlo_solution.c
	gcc -o monte_carlo_solution monte_carlo_solution.c

monte_carlo_init: monte_carlo_init.c
	gcc -o monte_carlo_init monte_carlo_init.c